name: sop-experiments
version: 0.1.0.0
dependencies:
  - base
  - generics-sop
  - generics-sop-lens
  - lens
ghc-options: -Wall
executables:
  sop-experiments:
    source-dirs: src
    main: Main.hs
